# VOD（動画配信サービス）データ定義
# - 各サービスの基本スペック・料金プラン・メリデメ・独自強み・推奨スコアを集約
# - generate.py / create_new_vod_pages.py から参照される
# - 料金・作品数は2025年時点の代表値。最新情報は公式サイトを参照
# - affiliate_url が空のものは A8 参加申請が通り次第埋める

# 推奨スコアの軸
SCORE_AXES = [
    {"key": "value", "label": "コスパ"},
    {"key": "library", "label": "作品数"},
    {"key": "exclusive", "label": "独占度"},
    {"key": "ui", "label": "使いやすさ"},
    {"key": "support", "label": "サポート"},
]

VODS = [
    {
        "id": "u-next",
        "name": "U-NEXT",
        "icon": "🎬",
        "tagline": "見放題33万本＋雑誌読み放題の最強総合型",
        "affiliate_url": "",  # TODO: A8 U-NEXT 提携URL
        "official_url": "https://www.unext.jp/",
        "monthly_fee": "2,189円（税込）",
        "free_trial_days": 31,
        "content_count": "見放題33万本＋レンタル6万本",
        "genres": ["映画", "海外ドラマ", "韓国ドラマ", "アニメ", "雑誌", "成人向け"],
        "target": ["とにかく作品数を求める人", "雑誌も読みたい人", "家族でアカウント共有したい人"],
        "devices": ["スマホ", "PC", "テレビ", "タブレット"],
        "features": [
            "見放題作品数が国内最大級",
            "毎月1,200ポイント付与（最新作レンタル可）",
            "4アカウントまで同時利用可",
            "雑誌150誌以上が読み放題",
        ],
        "weak_points": ["月額が他社より高め", "ポイントの繰越期限あり"],
        "pros": [
            "見放題33万本は国内No.1クラス",
            "毎月1,200ポイントで最新映画もレンタル可",
            "4アカウント無料で家族別ジャンルも同時視聴OK",
            "雑誌150誌＋電子書籍の購入もポイント利用可",
        ],
        "cons": [
            "月額2,189円は専門特化型VODの3〜4倍",
            "アダルトジャンルが含まれるため家族共有時は注意",
        ],
        "usp": [
            "1契約で映画・ドラマ・アニメ・雑誌をすべてカバー",
            "毎月もらえる1,200ポイントで実質1,000円以下相当",
        ],
        "pricing_plans": [
            {"name": "月額プラン", "fee": "2,189円（税込）/月", "note": "31日間無料体験あり"},
        ],
        "simultaneous_streams": 4,
        "download": True,
        "quality": "4K / フルHD / HD",
        "subtitles_dubbing": "主要作品で字幕・吹替に対応",
        "payment_methods": ["クレジットカード", "キャリア決済（ドコモ/au/ソフトバンク）", "Amazon決済", "ギフトコード"],
        "recommend_score": {"value": 4.0, "library": 5.0, "exclusive": 4.5, "ui": 4.0, "support": 4.0},
        "difficulty": "万能型",
    },
    {
        "id": "hulu",
        "name": "Hulu",
        "icon": "📺",
        "tagline": "海外ドラマと日テレ系番組に強いバランス型",
        "affiliate_url": "",  # TODO: A8 Hulu 提携URL
        "official_url": "https://www.hulu.jp/",
        "monthly_fee": "1,026円（税込）",
        "free_trial_days": 0,
        "content_count": "見放題14万本以上",
        "genres": ["海外ドラマ", "国内ドラマ", "アニメ", "バラエティ"],
        "target": ["海外ドラマ好き", "日テレ系番組をよく観る人", "FOX/HBO作品を観たい人"],
        "devices": ["スマホ", "PC", "テレビ", "タブレット"],
        "features": [
            "海外ドラマのラインナップが強い",
            "日テレ系の見逃し配信が充実",
            "全作品見放題でレンタル料なし",
        ],
        "weak_points": ["無料体験が現在停止中", "最新映画のレンタルなし"],
        "pros": [
            "海外ドラマ作品数が国内VOD屈指",
            "日テレ系ドラマ・バラエティの見逃し配信が即日反映",
            "全作品見放題のシンプル料金（追加課金なし）",
        ],
        "cons": [
            "無料体験が停止中で初期コストがかかる",
            "最新の劇場映画ラインナップは弱め",
        ],
        "usp": [
            "FOX・HBO・FXなど北米プレミアム局のドラマが充実",
            "日テレ系ドラマを地上波放送翌日に配信",
        ],
        "pricing_plans": [
            {"name": "月額プラン", "fee": "1,026円（税込）/月", "note": "全作品見放題・追加課金なし"},
        ],
        "simultaneous_streams": 1,
        "download": True,
        "quality": "フルHD / HD",
        "subtitles_dubbing": "主要海外ドラマは字幕・吹替の切替可",
        "payment_methods": ["クレジットカード", "キャリア決済", "PayPay", "iTunes Store決済"],
        "recommend_score": {"value": 3.5, "library": 4.0, "exclusive": 4.5, "ui": 4.5, "support": 4.0},
        "difficulty": "海外ドラマ向け",
    },
    {
        "id": "lemino",
        "name": "Lemino",
        "icon": "🎤",
        "tagline": "韓ドラ・K-POPライブの独占配信が豊富",
        "affiliate_url": "",  # TODO: A8 Lemino 提携URL
        "official_url": "https://lemino.docomo.ne.jp/",
        "monthly_fee": "990円（税込）",
        "free_trial_days": 31,
        "content_count": "見放題18万本以上",
        "genres": ["韓国ドラマ", "K-POP", "アニメ", "ライブ配信"],
        "target": ["韓ドラ・K-POPファン", "ライブ配信を観たい人", "ドコモユーザー"],
        "devices": ["スマホ", "PC", "テレビ", "タブレット"],
        "features": [
            "韓国コンテンツが充実",
            "音楽ライブの独占配信あり",
            "ドコモ以外でも契約可",
        ],
        "weak_points": ["旧dTVから刷新で混乱を招くUI", "無料パートと有料パートの境界が分かりにくい"],
        "pros": [
            "月額990円で韓ドラ・K-POPライブが見放題",
            "31日間の無料体験で十分試せる",
            "ドコモ非ユーザーも契約可能",
        ],
        "cons": [
            "全作品見放題ではなく、一部はレンタル別料金",
            "リニューアル直後はUIが不安定との声",
        ],
        "usp": [
            "K-POP独占ライブ配信が業界最多クラス",
            "韓ドラの最新話を地上波放送と同時配信",
        ],
        "pricing_plans": [
            {"name": "プレミアム", "fee": "990円（税込）/月", "note": "見放題＋ライブ独占含む"},
            {"name": "無料パート", "fee": "0円", "note": "登録なしで一部作品が観られる"},
        ],
        "simultaneous_streams": 4,
        "download": True,
        "quality": "4K / フルHD / HD",
        "subtitles_dubbing": "韓ドラ作品は字幕中心、一部吹替対応",
        "payment_methods": ["クレジットカード", "ドコモ払い", "App Store決済"],
        "recommend_score": {"value": 4.0, "library": 4.0, "exclusive": 4.5, "ui": 3.5, "support": 3.5},
        "difficulty": "K-POP/韓ドラ向け",
    },
    {
        "id": "dazn",
        "name": "DAZN",
        "icon": "⚽",
        "tagline": "Jリーグ・MLB・F1のライブ独占配信",
        "affiliate_url": "",  # TODO: A8 DAZN 提携URL
        "official_url": "https://www.dazn.com/ja-JP/",
        "monthly_fee": "4,200円（税込／DAZN Standard）",
        "free_trial_days": 0,
        "content_count": "スポーツ専門ライブ＋見逃し",
        "genres": ["サッカー", "野球", "F1", "テニス", "格闘技"],
        "target": ["スポーツ中継を観たい人", "Jリーグ・MLB・F1ファン"],
        "devices": ["スマホ", "PC", "テレビ", "タブレット"],
        "features": [
            "Jリーグ全試合をライブ配信",
            "MLB・F1・WTAなどグローバルスポーツ",
            "見逃し配信あり",
        ],
        "weak_points": ["スポーツ以外のコンテンツがない", "月額が高め", "値上げ幅が大きい"],
        "pros": [
            "Jリーグ全試合・MLB全試合を独占ライブ配信",
            "ハイライト・見逃し配信を試合終了直後にアーカイブ",
            "アンケートでも満足度が高く解約率も低め",
        ],
        "cons": [
            "月額4,200円はVOD最高水準",
            "スポーツ以外のドラマ・映画は一切配信なし",
        ],
        "usp": [
            "Jリーグ全試合の生中継権を保有（国内唯一）",
            "F1全戦のライブ・予選・FP含む完全配信",
        ],
        "pricing_plans": [
            {"name": "DAZN Standard 月額", "fee": "4,200円（税込）/月", "note": "全コンテンツ視聴可"},
            {"name": "DAZN Standard 年間プラン（一括）", "fee": "32,000円（税込）/年", "note": "実質月額2,667円"},
            {"name": "DAZN Global", "fee": "1,200円（税込）/月", "note": "海外コンテンツ中心の限定プラン"},
        ],
        "simultaneous_streams": 2,
        "download": False,
        "quality": "フルHD / HD",
        "subtitles_dubbing": "中継は実況解説の日本語音声",
        "payment_methods": ["クレジットカード", "デビットカード", "PayPay", "DAZN Prepaid Card"],
        "recommend_score": {"value": 3.0, "library": 3.5, "exclusive": 5.0, "ui": 4.0, "support": 3.5},
        "difficulty": "スポーツ特化",
    },
    {
        "id": "abema",
        "name": "ABEMAプレミアム",
        "icon": "📡",
        "tagline": "オリジナル番組とアニメ最新話に強いライト型",
        "affiliate_url": "https://px.a8.net/svt/ejp?a8mat=4B3K2P+15OD4I+4EKC+5YJRM",  # A8 ABEMA（提携中）
        "official_url": "https://abema.tv/",
        "monthly_fee": "1,080円（税込）",
        "free_trial_days": 14,
        "content_count": "見放題30,000本以上＋ライブチャンネル",
        "genres": ["アニメ", "オリジナルバラエティ", "格闘技", "麻雀", "ニュース"],
        "target": ["アニメと独自バラエティを観たい人", "Mリーグ・格闘技ファン"],
        "devices": ["スマホ", "PC", "テレビ", "タブレット"],
        "features": [
            "アニメ最新話の見逃し配信に強い",
            "オリジナル恋愛・バラエティが豊富",
            "Mリーグ・RIZINなど独占配信",
        ],
        "weak_points": ["映画ラインナップは弱め", "プレミアム加入しないと観られない番組がある"],
        "pros": [
            "アニメ最新話を地上波放送と同時配信",
            "オリジナル恋愛番組（今日好き等）が独占",
            "Mリーグ・RIZIN・将棋など独占ジャンル多数",
        ],
        "cons": [
            "ハリウッド大作・劇場映画の見放題は弱い",
            "無料部分との切り分けがやや分かりにくい",
        ],
        "usp": [
            "Mリーグ全試合をライブ独占配信（国内唯一）",
            "オリジナル恋愛番組のヒット作多数",
        ],
        "pricing_plans": [
            {"name": "プレミアム", "fee": "1,080円（税込）/月", "note": "全作品見放題＋ダウンロード可"},
            {"name": "ベーシック（無料）", "fee": "0円", "note": "広告付き／一部作品のみ"},
        ],
        "simultaneous_streams": 2,
        "download": True,
        "quality": "フルHD / HD",
        "subtitles_dubbing": "オリジナル番組は字幕オプションあり",
        "payment_methods": ["クレジットカード", "キャリア決済", "App Store決済", "Google Play決済"],
        "recommend_score": {"value": 4.0, "library": 3.5, "exclusive": 5.0, "ui": 4.0, "support": 3.5},
        "difficulty": "ライト層向け",
    },
    {
        "id": "danime",
        "name": "dアニメストア",
        "icon": "🎌",
        "tagline": "月額550円・アニメ網羅率No.1の特化型",
        "affiliate_url": "",  # TODO: A8 dアニメストア 提携URL
        "official_url": "https://anime.dmkt-sp.jp/",
        "monthly_fee": "550円（税込）",
        "free_trial_days": 31,
        "content_count": "アニメ5,800作品以上",
        "genres": ["アニメ"],
        "target": ["アニメだけ観られれば十分な人", "ランニングコストを抑えたい人"],
        "devices": ["スマホ", "PC", "テレビ", "タブレット"],
        "features": [
            "アニメ特化で作品網羅率が高い",
            "業界最安級の月額550円",
            "2.5次元舞台・声優ライブも配信",
        ],
        "weak_points": ["アニメ以外は観られない", "ドコモアカウント連携が必須（dアカウント）"],
        "pros": [
            "深夜アニメの新作網羅率は業界最高クラス",
            "月額550円でアニメ5,800作品が見放題",
            "声優ライブ・2.5次元舞台コンテンツも対象",
        ],
        "cons": [
            "アニメ以外（実写ドラマ・映画）は一切なし",
            "アカウントは1台のみ同時視聴",
        ],
        "usp": [
            "新作アニメの最速配信タイトル数で常時トップ",
            "声優ライブ・舞台の配信権が豊富",
        ],
        "pricing_plans": [
            {"name": "月額プラン", "fee": "550円（税込）/月", "note": "31日間無料体験あり"},
        ],
        "simultaneous_streams": 1,
        "download": True,
        "quality": "フルHD / HD",
        "subtitles_dubbing": "日本語音声中心、字幕は一部のみ",
        "payment_methods": ["クレジットカード", "ドコモ払い"],
        "recommend_score": {"value": 5.0, "library": 4.5, "exclusive": 4.0, "ui": 4.0, "support": 3.5},
        "difficulty": "アニメ特化",
    },
    {
        "id": "fod",
        "name": "FODプレミアム",
        "icon": "🎭",
        "tagline": "フジテレビ系ドラマと雑誌読み放題のセット",
        "affiliate_url": "",  # TODO: A8 FOD 提携URL
        "official_url": "https://fod.fujitv.co.jp/",
        "monthly_fee": "976円（税込）",
        "free_trial_days": 0,
        "content_count": "見放題8万本以上",
        "genres": ["フジテレビ系ドラマ", "バラエティ", "アニメ", "雑誌"],
        "target": ["フジテレビ系ドラマ・月9ファン", "雑誌も読みたい人"],
        "devices": ["スマホ", "PC", "テレビ", "タブレット"],
        "features": [
            "フジテレビ独占ドラマ・バラエティ",
            "雑誌130誌以上読み放題",
            "毎月最大1,300ポイント付与",
        ],
        "weak_points": ["他局ドラマは弱い", "無料体験は終了"],
        "pros": [
            "月9・木10など人気ドラマの見逃し＋過去回が独占",
            "雑誌130誌以上が追加料金なしで読み放題",
            "毎月1,300ポイントで最新作レンタルも可",
        ],
        "cons": [
            "TBS・テレ朝・日テレ系のドラマは観られない",
            "Amazonプライムビデオ等にも一部が配信されており重複が出る",
        ],
        "usp": [
            "フジテレビ系コンテンツの独占配信",
            "雑誌読み放題＋ポイント還元の二重特典",
        ],
        "pricing_plans": [
            {"name": "プレミアム", "fee": "976円（税込）/月", "note": "見放題＋雑誌＋ポイント"},
        ],
        "simultaneous_streams": 1,
        "download": True,
        "quality": "フルHD / HD",
        "subtitles_dubbing": "国内ドラマは字幕オプション一部対応",
        "payment_methods": ["クレジットカード", "Amazon決済", "App Store決済"],
        "recommend_score": {"value": 3.5, "library": 3.5, "exclusive": 4.5, "ui": 3.5, "support": 3.5},
        "difficulty": "フジテレビ派向け",
    },
    {
        "id": "dmm-tv",
        "name": "DMM TV",
        "icon": "🎟️",
        "tagline": "アニメ＋舞台＋韓ドラを550円で網羅",
        "affiliate_url": "",  # TODO: A8 DMM TV 提携URL
        "official_url": "https://tv.dmm.com/vod/",
        "monthly_fee": "550円（税込）",
        "free_trial_days": 30,
        "content_count": "見放題19万本以上",
        "genres": ["アニメ", "2.5次元舞台", "韓国ドラマ", "オリジナル", "成人向け"],
        "target": ["アニメ＋舞台＋韓ドラを安く観たい人", "DMMポイントを使いたい人"],
        "devices": ["スマホ", "PC", "テレビ", "タブレット"],
        "features": [
            "月額550円でアニメ網羅率が高い",
            "2.5次元舞台コンテンツが豊富",
            "DMMポイントが毎月550pt還元",
        ],
        "weak_points": ["独自UIが慣れるまで使いにくい", "成人ジャンルが目に入りやすい設計"],
        "pros": [
            "月額550円でアニメ・韓ドラ・舞台をまとめて視聴",
            "毎月550ポイント還元で実質無料",
            "DMM内のレンタル・購入にもポイント転用可",
        ],
        "cons": [
            "通常のVODと比べてジャンルナビゲーションがやや独特",
            "アダルトジャンルの導線が分かりやすく家族共有時は注意",
        ],
        "usp": [
            "2.5次元舞台コンテンツの配信権が国内最多クラス",
            "毎月550ポイント還元で実質無料に近い",
        ],
        "pricing_plans": [
            {"name": "月額プラン", "fee": "550円（税込）/月", "note": "30日間無料体験＋550pt還元"},
        ],
        "simultaneous_streams": 4,
        "download": True,
        "quality": "フルHD / HD",
        "subtitles_dubbing": "韓ドラ・舞台中心に字幕対応",
        "payment_methods": ["クレジットカード", "DMMポイント", "PayPay", "キャリア決済"],
        "recommend_score": {"value": 5.0, "library": 4.0, "exclusive": 4.0, "ui": 3.5, "support": 3.5},
        "difficulty": "コスパ重視",
    },
    {
        "id": "telasa",
        "name": "TELASA",
        "icon": "🦸",
        "tagline": "テレ朝系ドラマと特撮ヒーローに強い",
        "affiliate_url": "",  # TODO: A8 TELASA 提携URL
        "official_url": "https://www.telasa.jp/",
        "monthly_fee": "618円（税込）",
        "free_trial_days": 15,
        "content_count": "見放題1万本以上",
        "genres": ["テレビ朝日系ドラマ", "仮面ライダー", "戦隊", "刑事ドラマ"],
        "target": ["テレ朝系ドラマファン", "特撮を観たい人", "auユーザー"],
        "devices": ["スマホ", "PC", "テレビ", "タブレット"],
        "features": [
            "テレビ朝日系の独占配信",
            "仮面ライダー・戦隊シリーズに強い",
            "auスマートパスとセット割あり",
        ],
        "weak_points": ["全体の作品数は少なめ", "ジャンルが偏っている"],
        "pros": [
            "仮面ライダー・スーパー戦隊シリーズの過去作が網羅",
            "相棒など長寿ドラマの全シリーズが配信",
            "auユーザーは Pontaポイント還元あり",
        ],
        "cons": [
            "総作品数1万本は他社の1/10以下",
            "アニメ・洋画ラインナップは限定的",
        ],
        "usp": [
            "仮面ライダーシリーズの独占配信",
            "テレ朝系刑事ドラマの過去シリーズ全網羅",
        ],
        "pricing_plans": [
            {"name": "月額プラン", "fee": "618円（税込）/月", "note": "15日間無料体験あり"},
        ],
        "simultaneous_streams": 1,
        "download": True,
        "quality": "フルHD / HD",
        "subtitles_dubbing": "国内ドラマ中心で字幕は一部のみ",
        "payment_methods": ["クレジットカード", "auかんたん決済"],
        "recommend_score": {"value": 4.0, "library": 2.5, "exclusive": 4.5, "ui": 3.5, "support": 3.5},
        "difficulty": "テレ朝派向け",
    },
    {
        "id": "wowow",
        "name": "WOWOWオンデマンド",
        "icon": "🎼",
        "tagline": "音楽ライブ・テニス4大大会の独占配信",
        "affiliate_url": "",  # TODO: A8 WOWOW 提携URL
        "official_url": "https://wod.wowow.co.jp/",
        "monthly_fee": "2,530円（税込）",
        "free_trial_days": 30,
        "content_count": "ライブ＋オンデマンド多数",
        "genres": ["音楽ライブ", "テニス", "サッカー", "プロレス", "海外ドラマ"],
        "target": ["音楽ライブを観たい人", "テニス・プロレスファン"],
        "devices": ["スマホ", "PC", "テレビ", "タブレット"],
        "features": [
            "国内外アーティストのライブ独占配信",
            "テニス4大大会フル中継",
            "オリジナル海外ドラマ・映画が高品質",
        ],
        "weak_points": ["月額が高め", "ジャンルがやや偏る"],
        "pros": [
            "国内外アーティストのライブ独占配信が圧巻",
            "テニス4大大会（全豪・全仏・ウィンブルドン・全米）を完全配信",
            "WOWOWオリジナル映画・ドラマの賞獲得作品多数",
        ],
        "cons": [
            "月額2,530円はVODでも高額の部類",
            "アニメ・最新邦画の見放題は弱い",
        ],
        "usp": [
            "テニス4大大会全試合の独占配信",
            "国内外ライブ配信のラインナップが業界トップクラス",
        ],
        "pricing_plans": [
            {"name": "月額プラン", "fee": "2,530円（税込）/月", "note": "WOWOWオンデマンド単独契約"},
            {"name": "BS放送＋オンデマンド", "fee": "2,530円（税込）/月", "note": "BSチューナー必要・契約料同額"},
        ],
        "simultaneous_streams": 5,
        "download": False,
        "quality": "4K / フルHD / HD",
        "subtitles_dubbing": "ライブは原語音声中心、ドラマは字幕・吹替対応",
        "payment_methods": ["クレジットカード", "デビットカード"],
        "recommend_score": {"value": 3.0, "library": 3.5, "exclusive": 5.0, "ui": 3.5, "support": 4.0},
        "difficulty": "ハイエンド",
    },
    {
        "id": "sukapa",
        "name": "スカパー!",
        "icon": "🛰️",
        "tagline": "50ch以上の専門チャンネル＋プロ野球12球団完全網羅",
        "affiliate_url": "https://px.a8.net/svt/ejp?a8mat=4B3K2P+51L922+461Y+6D4GI",  # A8 スカパー!（提携中）
        "official_url": "https://www.skyperfectv.co.jp/",
        "monthly_fee": "3,960円〜（基本パック・税込）",
        "free_trial_days": 0,
        "content_count": "50チャンネル以上＋番組配信",
        "genres": ["プロ野球", "サッカー", "ゴルフ", "F1", "映画", "海外ドラマ", "韓国ドラマ", "アニメ", "音楽", "ニュース"],
        "target": ["プロ野球を観たい人（巨人戦含む）", "海外ドラマ専門局を観たい人", "多チャンネル契約に慣れている人"],
        "devices": ["テレビ（BS/CSアンテナ）", "スマホ", "PC", "タブレット"],
        "features": [
            "50チャンネル以上の専門局",
            "プロ野球セットでセ・パ12球団完全網羅",
            "映画専門チャンネル多数",
            "番組配信でスマホ・PCでも視聴可能",
            "加入月料金無料",
        ],
        "weak_points": [
            "本格利用には月額3,960円〜と高め",
            "BS/CSアンテナの環境が必要",
            "パック選びが複雑",
        ],
        "pros": [
            "プロ野球12球団のホーム試合を完全網羅（業界唯一）",
            "海外ドラマ・韓ドラの専門チャンネルが豊富",
            "映画専門チャンネルでクラシックから新作まで網羅",
            "加入月の料金が無料（実質お試し可）",
        ],
        "cons": [
            "VODと比べて月額が高い",
            "アンテナ環境がない場合は工事が必要",
            "パック・チャンネル選びの判断軸が多い",
        ],
        "usp": [
            "プロ野球12球団のホーム試合配信は国内唯一（DAZNと差別化）",
            "海外ドラマ・韓ドラ・映画の専門チャンネル数が業界最多",
            "加入月料金無料で短期視聴のキャンペーン利用にも向く",
        ],
        "pricing_plans": [
            {"name": "基本料", "fee": "429円（税込）/月", "note": "別途チャンネル/パック料金が必要"},
            {"name": "スカパー!基本パック", "fee": "3,960円（税込）/月", "note": "50ch以上の人気専門局"},
            {"name": "スカパー!プロ野球セット", "fee": "4,054円（税込）/月", "note": "プロ野球12球団のホーム試合完全網羅"},
            {"name": "スカパー!サッカーセット", "fee": "3,000円（税込）/月", "note": "海外サッカー中継"},
        ],
        "simultaneous_streams": 1,
        "download": True,
        "quality": "4K / フルHD / HD",
        "subtitles_dubbing": "海外ドラマは字幕・吹替の切替可、スポーツは日本語実況",
        "payment_methods": ["クレジットカード", "口座振替"],
        "recommend_score": {"value": 3.0, "library": 4.5, "exclusive": 5.0, "ui": 3.0, "support": 3.5},
        "difficulty": "多チャンネル特化",
    },
]

# 比較記事で使う比較軸の定義（順序が表の列順になる）
COMPARE_AXES = [
    {"key": "monthly_fee", "label": "月額料金"},
    {"key": "free_trial_days", "label": "無料体験"},
    {"key": "content_count", "label": "作品数"},
    {"key": "simultaneous_streams", "label": "同時視聴"},
    {"key": "quality", "label": "画質"},
    {"key": "difficulty", "label": "得意ジャンル"},
]

QUIZ_QUESTIONS = [
    {
        "id": "genre",
        "text": "一番観たいジャンルはどれですか？",
        "options": [
            {"value": "drama_kr", "label": "韓国ドラマ・K-POP"},
            {"value": "anime", "label": "アニメ"},
            {"value": "sports", "label": "スポーツ中継"},
            {"value": "movie", "label": "映画・海外ドラマ"},
        ],
    },
    {
        "id": "budget",
        "text": "月額予算はどのくらいまでOKですか？",
        "options": [
            {"value": "low", "label": "〜600円（最安重視）"},
            {"value": "mid", "label": "〜1,200円（標準）"},
            {"value": "high", "label": "2,000円以上もOK"},
        ],
    },
    {
        "id": "device",
        "text": "主にどこで観ますか？",
        "options": [
            {"value": "phone", "label": "スマホ・通勤中"},
            {"value": "tv", "label": "テレビでじっくり"},
            {"value": "share", "label": "家族とシェア"},
        ],
    },
]
